enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0005
    level: discard
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
